name: 'Deploy to Pages'

on:
  push:
    branches:
      - main

jobs:
  deploy-demo:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: './example/'
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup bun env ğŸ°
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies ğŸš€
        run: bun install

      - name: Run build ğŸ
        run: bun run build

      - name: Deploy to GitHub Pages ğŸš€
        uses: peaceiris/actions-gh-pages@v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./example/dist
          cname: v-offline.netlify.app
